artifactId: contract
artifactVersion: "0.3.0"
groupId: "com.github.aaronp"
packageName: "contract"
modelPackage: "contract.model"
apiPackage: "contract.api"
gitRepoId: "counterparty"
gitUserId: "aaronp"